### ISSUE TITLE
Downloading compiler v3.10.8 still fails

### ISSUE THREAD

**Issue by AGraber** [Southclaws/sampctl#233] opened 2018-08-07 23:38 UTC
```samp@agraber:~/OmegaZone$ sampctl p build live
INFO: Usage metrics are active. See https://github.com/Southclaws/sampctl/wiki/Usage-Metrics for more information.
INFO: Downloading compiler package v3.10.8
ERROR: Failed to execute compiler
ERROR: if you're on a 64 bit system this may be because the system is not set up to execute 32 bit binaries
ERROR: please enable this by allowing i386 packages and/or installing g++-multilib
failed to compile package entry: failed to execute compiler: fork/exec /home/samp/.samp/pawn/3.10.8/pawncc: no such file or directory
```

**Comment by Southclaws** [comment] 2018-08-08 08:03
Again? I've fixed this twice... try clearing the cache of all compiler archives. All I can think of is someone on the compiler team messed with the directory structure of the release archive.

**Comment by AGraber** [comment] 2018-08-09 13:04
More relevant logs:
```
root@oceano:~# curl https://raw.githubusercontent.com/Southclaws/sampctl/master/                                                                                                                               install-deb.sh | sh
-bash: curl: command not found
root@oceano:~# apt install curl
[...]
Setting up curl (7.52.1-5+deb9u6) ...
root@oceano:~# sudo dpkg --add-architecture i386
root@oceano:~# sudo apt update && sudo apt install -y g++-multilib
[...]
Setting up g++-multilib (4:6.3.0-4) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
root@oceano:~# curl https://raw.githubusercontent.com/Southclaws/sampctl/master/install-deb.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   373  100   373    0     0   2118      0 --:--:-- --:--:-- --:--:--  2119
Selecting previously unselected package sampctl.
(Reading database ... 42042 files and directories currently installed.)
Preparing to unpack tmp.deb ...
Unpacking sampctl (1.8.25) ...
Setting up sampctl (1.8.25) ...
root@oceano:~# git clone https://github.com/sampctl/samp-bare
-bash: git: command not found
root@oceano:~# apt install git
[...]
root@oceano:~# git clone https://github.com/sampctl/samp-bare
Cloning into 'samp-bare'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.
root@oceano:~# cd samp-bare
root@oceano:~/samp-bare# sampctl p ensure
INFO: Usage metrics are active. See https://github.com/Southclaws/sampctl/wiki/Usage-Metrics for more information.
INFO: sampctl/samp-bare successfully ensured dependency files for github.com/sampctl/samp-stdlib
INFO: sampctl/samp-bare successfully ensured dependency files for github.com/sampctl/pawn-stdlib
INFO: ensured dependencies for package
root@oceano:~/samp-bare# sampctl p build
INFO: Usage metrics are active. See https://github.com/Southclaws/sampctl/wiki/Usage-Metrics for more information.
updating compiler list...
INFO: Downloading compiler package v3.10.4
INFO: Build  successful with 0 problems
root@oceano:~/samp-bare# cd ..
root@oceano:~# git clone https://github.com/AGraber/OmegaZone
Cloning into 'OmegaZone'...
Username for 'https://github.com': AGraber
Password for 'https://AGraber@github.com':
remote: Counting objects: 432, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 432 (delta 65), reused 122 (delta 41), pack-reused 282
Receiving objects: 100% (432/432), 4.24 MiB | 5.78 MiB/s, done.
Resolving deltas: 100% (197/197), done.
root@oceano:~# cd OmegaZone
root@oceano:~/OmegaZone# sampctl p ensure
INFO: Usage metrics are active. See https://github.com/Southclaws/sampctl/wiki/Usage-Metrics for more information.
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/sampctl/samp-stdlib:0.3.7-R2-2-1
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/sampctl/pawn-stdlib
INFO: Zeex/samp-plugin-crashdetect:v4.19 downloading plugin resource for linux
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/Zeex/samp-plugin-crashdetect:v4.19
INFO: samp-incognito/samp-streamer-plugin:v2.9.3 downloading plugin resource for linux
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/samp-incognito/samp-streamer-plugin:v2.9.3
INFO: maddinat0r/sscanf:v2.8.2 downloading plugin resource for linux
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/maddinat0r/sscanf:v2.8.2
INFO: pBlueG/SA-MP-MySQL:R41-4 downloading plugin resource for linux
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/pBlueG/SA-MP-MySQL:R41-4
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/urShadow/Pawn.CMD:3.2.0
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/urShadow/Pawn.Regex:1.1.2
WARN: failed to ensure package github.com/emmet-jones/New-SA-MP-Callbacks: no pawn.json/pawn.yaml present
WARN: failed to ensure package github.com/karimcambridge/SAMP-foreach: no pawn.json/pawn.yaml present
INFO: AGraber/OmegaZone successfully ensured dependency files for github.com/ziggi/FCNPC:v1.8.2
updating runtimes list...
INFO: Downloading package 0.3.7 into /root/OmegaZone
INFO: github.com/urShadow/Pawn.CMD:3.2.0 downloading plugin resource for linux
INFO: github.com/urShadow/Pawn.Regex:1.1.2 downloading plugin resource for linux
INFO: github.com/ziggi/FCNPC:v1.8.2 downloading plugin resource for linux
ERROR: failed to ensure: failed to ensure scripts: filterscript '123' is missing its .amx file from the filterscripts directory, filterscript 'Mapas' is missing its .amx file from the filterscripts directory, filterscript 'ls_elevator' is missing its .amx file from the filterscripts directory, filterscript 'ls_beachside' is missing its .amx file from the filterscripts directory
root@oceano:~/OmegaZone# sampctl p build live
INFO: Usage metrics are active. See https://github.com/Southclaws/sampctl/wiki/Usage-Metrics for more information.
INFO: Downloading compiler package v3.10.8
ERROR: Failed to execute compiler
ERROR: if you're on a 64 bit system this may be because the system is not set up to execute 32 bit binaries
ERROR: please enable this by allowing i386 packages and/or installing g++-multilib
failed to compile package entry: failed to execute compiler: fork/exec /root/.samp/pawn/3.10.8/pawncc: no such file or directory
root@oceano:~/OmegaZone#
```
Complete (contains a bunch of install stuff which may not be useful
https://pastebin.com/Z9F1BMnU

Currently decompressing it manually works for now, so no big deal atm.

**Comment by Southclaws** [comment] 2018-08-18 14:42
Found the cause: https://github.com/pawn-lang/compiler/issues/358

Fixed now, that issue should make sure it doesn't happen again!

**Closed** 2018-08-18 15:51 UTC

**Comment by daniilkorochansky** [comment] 2026-06-17 16:36
Ubuntu 22.04 amd64 (WSL)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7f8c1a76-4cef-4003-b896-e121fb5bdd17" />

**Comment by ADRFranklin** [comment] 2026-06-17 16:39
@daniilkorochansky not sure why you didn't create a new issue, but you need to install 32bit libs for ubuntu. 
```
dpkg --add-architecture i386 && apt update && apt install -y g++-multilib
```

also you are using compiler v3.10.11 and not 3.10.8, so has nothing to do with this issue

**Comment by daniilkorochansky** [comment] 2026-06-17 16:52
> [@daniilkorochansky](https://github.com/daniilkorochansky) not sure why you didn't create a new issue, but you need to install 32bit libs for ubuntu.
> 
> ```
> dpkg --add-architecture i386 && apt update && apt install -y g++-multilib
> ```
> 
> also you are using compiler v3.10.11 and not 3.10.8, so has nothing to do with this issue

Fixed!

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/69c2c56f-c281-4a11-8454-b446ae4b7ad7" />
