### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by Lathrel** [Southclaws/sampctl#130] opened 2018-03-14 12:42 UTC
Hi,
After I updated sampctl to version 1.7.0 I'm having this problem when typing any command.
I'm using Windows 10.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9705f5]
 
goroutine 1 [running]:
github.com/Southclaws/sampctl/rook.resolveResourcePaths.func1(0xc0423202d0, 0x81, 0x0, 0x0, 0xb86440, 0xc0426187e0, 0x20, 0xa7b300)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/load.go:175 +0x75
path/filepath.Walk(0xc0423202d0, 0x81, 0xc04219f100, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/path/filepath/path.go:401 +0x73
github.com/Southclaws/sampctl/rook.resolveResourcePaths(0x0, 0xc042056840, 0x57, 0xc042369780, 0x3f, 0xb0b488, 0x4, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/load.go:174 +0x848
github.com/Southclaws/sampctl/rook.ResolveDependencies.func1(0xb102a5, 0xa, 0xc04236c2d0, 0x4, 0xc04236c2d5, 0x17, 0xc04236c2ed, 0x7, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/load.go:111 +0x7b6
github.com/Southclaws/sampctl/rook.ResolveDependencies(0xc042354380, 0xb0e56d, 0x7, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/load.go:138 +0x65a
github.com/Southclaws/sampctl/rook.PackageFromDir(0xaf6d01, 0xc042369500, 0x32, 0xb0e56d, 0x7, 0x0, 0x0, 0xc0426182d0, 0xb0dd70, 0x1, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/load.go:48 +0x348
main.packageEnsure(0xc0420a8580, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/package_ensure.go:38 +0x17b
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xa05f60, 0xb386e0, 0xc0420a8580, 0xc042c73000, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xcf
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb0cb74, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb19363, 0x16, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa3d
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc04208eb60, 0xc0420a82c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0xa17
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0xb0e11b, 0x7, 0x0, 0x0, 0xc0426042b0, 0x1, 0x1, 0xb1e6c3, 0x1c, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x8e0
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb0e11b, 0x7, 0x0, 0x0, 0xc0426042b0, 0x1, 0x1, 0xb1e6c3, 0x1c, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x124d
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc04208e820, 0xc04204a0c0, 0x3, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6a7
main.main()
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:243 +0x17df
```

**Comment by Dayvison** [comment] 2018-03-14 13:59
This happens after update the sampctl to 1.7.0
To fix this you can:
```bash
rm dependencies -r
sampctl p ensure
```

**Comment by Lathrel** [comment] 2018-03-14 15:04
Yes, but I can't ensure sscanf, crashdetect.
I get the same error!

**Comment by Southclaws** [comment] 2018-03-14 15:06
Thanks for reporting, I'm going to try to fix this right now and get a version released asap for you. Can you provide a `pawn.json` you were using? Feel free to remove any private information or private dependency repositories.

**Comment by Southclaws** [comment] 2018-03-14 15:28
I've released 1.7.1

**Comment by Lathrel** [comment] 2018-03-14 15:31
There is not much to show here.

pawn.json
```
{
    "user": "Lathrel",
    "repo": "roleplay",
    "entry": "gamemodes/src/main.pwn",
    "output": "gamemodes/main.amx",
    "dependencies": [
        "Southclaws/samp-stdlib",
        "Zeex/samp-plugin-crashdetect",
        "maddinat0r/sscanf",
        "Zeex/amx_assembly",
        "pawn-lang/YSI-Includes",
        "samp-incognito/samp-streamer-plugin",
        "Southclaws/formatex",
        "pBlueG/SA-MP-MySQL",
        "maddinat0r/samp-mysql-yinline-include",
        "Southclaws/samp-logger"
    ]
}
```

**Comment by Southclaws** [comment] 2018-03-14 15:39
Thanks, I'll do some testing and ensure the issue is resolved.

1.7.1 will be released once the TravisCI tests and deployment have finished, you can track progress here: https://travis-ci.org/Southclaws/sampctl

**Closed** 2018-03-14 15:45 UTC

**Comment by Southclaws** [comment] 2018-03-14 18:38
Okay so it turns out this was a Windows specific issue caused by the Go directory walking implementation for Windows.

1.7.2 resolves this for good - tested on Windows thanks to Debjit on Discord.
