### ISSUE TITLE
Having a runtime.includes section blocks building

### ISSUE THREAD

**Issue by kristoisberg** [Southclaws/sampctl#279] opened 2018-12-25 14:03 UTC
```
INFO: kristoisberg/samp-gps-plugin read package from directory C:\Users\Kristo Isberg\Documents\gps-plugin
INFO: kristoisberg/samp-gps-plugin building dependency tree and ensuring cached copies
INFO: |- kristoisberg/samp-gps-plugin is parent
INFO: |- added target path for resource includes: C:\Users\Kristo Isberg\Documents\gps-plugin\dependencies\.resources\samp-gps-plugin-f2eb00
INFO: using include path C:\Users\Kristo Isberg\Documents\gps-plugin\dependencies\.resources\samp-gps-plugin-f2eb00
failed to list dependency include path: C:\Users\Kristo Isberg\Documents\gps-plugin\dependencies\.resources\samp-gps-plugin-f2eb00: open C:\Users\Kristo Isberg\Documents\gps-plugin\dependencies\.resources\samp-gps-plugin-f2eb00: The system cannot find the path specified.
```

```
"resources": [
	{
		"name": "GPS-windows.zip",
		"platform": "windows",
		"archive": true,
		"includes": [
			"GPS.inc"
		],
		"plugins": [
			"GPS.dll"
		],
		"files": {
			"GPS.dat": "scriptfiles/GPS.dat"
		}
	},
]
```

Removing the `includes` section fixes the issue. I suppose it just shouldn't be trying to use resource includes (or resources in general) when building the package directly.

**Comment by Southclaws** [comment] 2018-12-26 16:17
This was caused by the root node of the tree (aka the "parent") being treated like all its children when resolving resources. So during build, sampctl would see that some dependency required resources and would go and try to fetch those resources.

This has been fixed in 1.8.37 - Now, it ignores resources for the root node. To build+run, I believe you'll need to add a runtime config specifying the name of the local plugin file.

**Closed by Southclaws** 2018-12-26 16:17 UTC
